### ISSUE TITLE
Render newlines in DDoc popup

### ISSUE THREAD

**Issue by JinShil** [DDT-IDE/DDT#110]
My DDoc comment looks like this:
```
/********************************************************************************
 Port 2 
 These bits are written by software to configure the I/O direction mode.
 00: Input (reset state)
 01: General purpose output mode
 10: Alternate function mode
 11: Analog mode
*/
alias MODER2 = BitField!(5, 4, Mutability.rw);
```
But it's rendered in the DDoc popup as...
![ddoc](https://cloud.githubusercontent.com/assets/6023641/7383224/9360d510-ee56-11e4-93be-1c76ae0170d0.png)
That is, the newlines are not preserved making it a little more difficult to read.

Implementing a way to preserved the DDoc appearance as it is written it the comment would be most welcome.  Thank you.

**Comment by bruno-medeiros** [comment]
I agree preserving the newlines in the comment source would be nicer. Unfortunately, that is not the standard way that DMD generates DDoc - it ignores newlines. So if DDT were to preserve the newlines, it would be presenting DDoc in a non-standard way. This is not ideal. Then other users would see the doc in a different way, unless they were using DDT as well. 

I might still add this as an editor preference regardless, but I'm unsure...
