### ISSUE TITLE
Can't run target in a case sensitive OS  

### ISSUE THREAD

**Issue by Superstar64** [DDT-IDE/DDT#115]
![ddt screenshot](https://cloud.githubusercontent.com/assets/6628920/9219104/6bdcd1b8-40a6-11e5-9132-fb60f43526de.png)

**Comment by bruno-medeiros** [comment]
Hum, odd. What are the contents of your dub.json file ?

**Comment by Superstar64** [comment]
{
	"name" : "Test",
	"description" : "Hello World - A minimal DUB bundle.",
	"dependencies" : {
	}
}


$ dub --version
DUB version 0.9.23, built on Apr  4 2015


The excutables dub makes seems to always be in lowercase

**Comment by bruno-medeiros** [comment]
> The excutables dub makes seems to always be in lowercase

Seems like it's a DUB problem then. Although, actually, it is recommended that DUB package names be lowercase anyways. So you should have `"name" : "test"` instead.
If you still want the executable to be cased, you should use the `"targetName" : ` field
