### ISSUE TITLE
foreach(const ref x; y) is invalid syntax

### ISSUE THREAD

**Issue by tomerfiliba** [DDT-IDE/DDT#117]
code such as 
```
foreach(x, const ref y; myTable) {
    something();
}
```

is considered invalid syntax (specifically it's the ``const`` that causes it) and everything from that point on is marked as error in the file. Using latest DDT.

**Comment by bruno-medeiros** [comment]
Workaround: write `ref const y;` instead

**Comment by bruno-medeiros** [comment]
Workaround: write `foreach(x, const ref y; myTable)` instead

**Comment by bruno-medeiros** [comment]
Workaround: write `ref const y;` instead
