### ISSUE TITLE
Compiled binary name in small letters only

### ISSUE THREAD

**Issue by LinAGKar** [DDT-IDE/DDT#118]
When a D project whose name includes capital letters is compiled, the file name of the resulting binary will be in small letters only. Then, when Eclipse tries to run the project it look for a binary with the correct capitalization, an will not find it.

Eclipse Platform 4.5.0.I20150603-2000
DDT 0.13.1.v201508241541
openSUSE 13.2 64

**Comment by bruno-medeiros** [comment]
The resulting binary for  a D project should not depend on the project name, but just one the name of the DUB package. What are the contents of your dub.json? Did you try this with a freshly created project?

**Comment by LinAGKar** [comment]
I created an new project named "Test"
dub.json:
```
{
	"name" : "Test",
	"description" : "Hello World - A minimal DUB bundle.",
	"dependencies" : {
	}
}
```
Eclipse looks for "Test" when I try to run the project, however the compiled binary is named "test".

**Comment by bruno-medeiros** [comment]
Really? What dub version do you have? I tried with dub-0.9.24-linux-x86_64.tar.gz and the generated binary had uppercase letters.

In any case, it doesn't matter. DUB packages names should be all lower-case, as can be seen by the error message that DUB outputs when you try to build such DUB package:
`WARNING: DUB package names should always be lower case. Please modify the "name" field`...

I'm gonna resolve this by having the D project wizard always generate the "name" field in lowercase.
