### ISSUE TITLE
Dark theme color scheme is applied to light theme

### ISSUE THREAD

**Issue by mbierlee** [DDT-IDE/DDT#120]
I've become a real fan of the Dark Theme since DDT now supports it too. But I noticed that the dark theme syntax colors are also applied to the light theme. This makes certain parts, such as string literals, harder to read.

Is this intended behavior? I think it's best to change it back to the "usual" color scheme for light themes.

(I'm using Eclipse Mars.1 on Windows 10)

**Comment by bruno-medeiros** [comment]
No, the dark theme syntax colors are not supposed to be applied to the light theme, that would defeat the purpose of them being configurable. I can't replicate any such error though.

The only bug I found is that the Build/Tools Console preference page is not updated after a theme change, until after you close the preferences dialog, and open it again.

**Comment by mbierlee** [comment]
Here's a screenshot from the editor with the dark and light theme next to each other:
![image](https://cloud.githubusercontent.com/assets/1678927/11614915/22ab1376-9c52-11e5-8184-9ad1f2f6908f.png)

Notice how most of the colors are re-used in the light theme. Some colors such as the yellow string literals and the purple type definition of hasOption() don't have a high contrast with their background in the light theme.
Some colors aren't (completely) the same such as the purples of keywords and the "true"/"false" keywords have completely different colors.

**Comment by bruno-medeiros** [comment]
Technically the color default for dark theme are different from light theme, it's just that the difference is very minor for a few of the source items (like strings). You can see the RGB defaults here: https://github.com/DDT-IDE/DDT/blob/master/plugin_ide.ui/src/mmrnmhrm/ui/text/DeeColorPreferences.java

Are you suggesting that the colors for dark theme have more contrast then?

**Comment by bruno-medeiros** [comment]
Technically the color default for dark theme are different from light theme, it's just that the difference is very minor for a few of the source items (like strings). You can see the RGB defaults here: https://github.com/DDT-IDE/DDT/blob/master/plugin_ide.ui/src/mmrnmhrm/ui/text/DeeColorPreferences.java  (first RGB parameter is light theme, second one is dark theme)

Are you suggesting that the colors for dark theme have more contrast then?

**Comment by mbierlee** [comment]
Ah I see. If you compare the dark and light themes of the Java editor you will see that the dark theme has a wide variety of colors while the light theme sticks to the old blues and greens because properly contrasting colors on a white background is trickier.

I suggest to make the light colors darker or revert the light theme color scheme back to what it was before.
