### ISSUE TITLE
Macro $(D) renders white in white field in DDoc popup.

### ISSUE THREAD

**Issue by KarlHeesch** [DDT-IDE/DDT#129]
![writeln](https://cloud.githubusercontent.com/assets/7713146/13117387/ffeb36ae-d59f-11e5-8867-c37c261e6948.png)

**Comment by bruno-medeiros** [comment]
Which OS is that? In Windows I still get a yellow background (instead of black) even with Dark Theme

**Comment by bruno-medeiros** [comment]
Ah nevermind, I get that result with Ubuntu Linux.

**Comment by KarlHeesch** [comment]
Right, it has been Ubuntu (Kubuntu).

Am 13.05.2016 um 13:31 schrieb Bruno Medeiros:
