### ISSUE TITLE
Improve: implement indent lines (ctrl+i) functionality

### ISSUE THREAD

**Issue by vadim-goryunov** [DDT-IDE/DDT#132]
Please implement indent lines (ctrl+i) functionality available in CDT or JDT.
Manually indenting the lines is very inconvenient.
Formatting the code (Ctrl+F) feature would be nice to have too.

**Comment by bruno-medeiros** [comment]
Code formatting (using dfmt) has already been added (but not released yet). But there is no way currently to use dfmt for just indentation.

**Comment by vadim-goryunov** [comment]
I think dfmt is good enough
