### ISSUE TITLE
The root README.md file is confusing to new DDT users

### ISSUE THREAD

**Issue by poliklosio** [DDT-IDE/DDT#138]
This is a request for a very small change which can improve first 5 minutes with DDT for new users.

The root README.md file begins with

> Developers Guide
> Setting up the development environment:

There are 2 problems with this:

1. Its confusing to _users_ of DDT.
So lets say I'm a software developer who would like to start using DDT to program some D code, This is the main README file of eclipse DDT project, so i should read it and start doing the things outlined at the beginning, correct?
Wrong! This is the information for developers of _DDT itself_.
2. The repository doesn't appear to contain the instructions of using the software, which is itself unusual and unexpected. 
The main github page was the second result that Google returned for me after I searched for "eclipse ddt". The website ddt-ide.github.io doesn't appear on the first page of the search results at all. The marketplace.eclipse.org/content/ddt was the first, but the github result points to the familiar place (github), so I clicked it first.

Please, add the link to the website (http://ddt-ide.github.io/) and the installation instructions 
(https://github.com/DDT-IDE/DDT/blob/latest/documentation/Installation.md) at the top of the root README file.

**Comment by bruno-medeiros** [comment]
I am aware of the distinction between DDT users and DDT contributors, which is why the README is  about DDT contributors/developers. There is already a link at the top of https://github.com/DDT-IDE/DDT/ to the user website ( http://ddt-ide.github.io/ ). It makes more sense for the link to be there, since this way the users don't have to scroll down the repository root to get to the README.md

**Comment by poliklosio** [comment]
The first time I looked at the github page, I overlooked the link. Anyone who is used to github is going to look at the README file, as that is what is shown by every other project.
Please, add the link also there.
DDT probably has 10 times more users than contributors. Please, optimize for the users, not for contributors.

**Comment by bruno-medeiros** [comment]
If people are looking straight at the README, whilst overlooking the project link at the top of the page, they are doing things wrong. 

Still, it doesn't hurt either way, so I've added the project link to the top of the README.

**Comment by poliklosio** [comment]
Thats the idea. A little redundancy in an introductory text doesn't hurt and may prevent someone from getting lost.
Thank you!
