### ISSUE TITLE
Eclipse-internal variable substitutions not resolved in Run Configurations/Environment tab

### ISSUE THREAD

**Issue by aubade** [DDT-IDE/DDT#139]
When setting per-Run Configuration environment variables, using eclipse substitutions, said substitutions do not appear to be properly resolved, at least on Win32 (I haven't yet tested this on linux or any other platforms yet)

It's pretty easy to illustrate this; create a project with this source file:

```
import std.stdio;
import std.process;

void main() {
	writeln("Eclipse project name: ", environment.get("PROJNAME", "Name not found"));
}
```
Then create a run configuration for it, and in the environment tab, make a variable named ```PROJNAME``` and set its value to ```${project_name}```; It should return whatever project is currently active in eclipse at the time you hit the run button, but here it just prints ${project_name}.

**Comment by aubade** [comment]
Unfortunately, this still seems to be an issue in the 1.0.1.v201606011426 release, with the same symptoms. I uninstalled and reinstalled DDT just to make sure it wasn't an issue in my installatian.

**Comment by aubade** [comment]
(I suspect the fix may just not have gotten baked into the release files)

**Comment by bruno-medeiros** [comment]
Oh, run configurations! What happened is that I fixed this for the env vars in Build Target execution, I thought that's where the problem was (and indeed it was buggy there as well). Will fix here as well

**Comment by bruno-medeiros** [comment]
Ok, I believe it is fixed now.
