### ISSUE TITLE
Executable in /workspace/[Project Name]/d Doesn't Exist

### ISSUE THREAD

**Issue by MggMuggins** [DDT-IDE/DDT#147]
I don't know if this is a problem with the DDT (pretty sure it's not), or just something I did wrong with installation (probably this one, but I figured this was the best place to come for help), but I'm getting an error when I try to launch the project. Error:

'Launching [Project Name] - (default)' has encountered a problem.
Executable file (/home/[Me]/workspace/[Project Folder]/d) doesnt exist.

I'm a newbie to Eclipse and D in general, but I think I have enough of a clue that I can get this running. This error happens when I press the "Run" button. I can use eclipse to write my source files, and then compile with the dmd and run with the command line, but that is a pain, and frankly would be nice to see eclipse do what I tell it to. Probably just making some mistake, but enlightenment would be greatly appreciated. (I'm running Ubuntu 16.04, if that changes anything, also (what I think) is the latest version of the DDT (installed it yesterday) and eclipse (Neon 4.6, installed via the installer)).
~Sam

**Comment by bruno-medeiros** [comment]
After you try to launch the project, check the console view for the D build output, see if there is anything wrong there.

**Comment by MggMuggins** [comment]
The terminal output is as follows (Quite short):
`************  Building D project: D  ************
>> Running: /usr/bin/dub build
Performing "debug" build using dmd for x86_64.
d ~master: building configuration "library"...
  ^^^ Terminated, exit code: 0 ^^^
************  Build terminated.  ************`

**Comment by bruno-medeiros** [comment]
If it says `building configuration "library"` then it's not generating any executable. Do you have a `main` function in your code? DUB needs to find it to be able to generate an executable

**Comment by MggMuggins** [comment]
![void main](https://cloud.githubusercontent.com/assets/16041213/19280050/b1fb203e-8fa9-11e6-887d-66162f35023d.png)
There are the first few lines of code, including my imports. There is a closing curly brace at the end of the program.

**Comment by bruno-medeiros** [comment]
Where is that source file located?

**Comment by MggMuggins** [comment]
in

/home/[My Name]/workspace/[Project Name]/src
 
where workspace is my eclipse workspace and [Project Name] is my project. I am running on Linux, as you may be able to tell by the path. I did update this workspace from the version of eclipse that is in the Ubuntu repositories, so it might be an issue with that.

**Comment by bruno-medeiros** [comment]
I can't figure out what's wrong. In any case, if you open the command line and run `dub build` in the project directory, and you still don't get an executable, it's not a DDT problem any way.

**Comment by MggMuggins** [comment]
I ran that, and there are some dub files there, but there is no exec in the projecct directory. I have no idea why this would be. I'm going to try deleting the files I created using the dmd and see if that does anything...

**Comment by MggMuggins** [comment]
Here is some more output:

'''************  Resolving DUB project: D  ************
>> Running: /usr/bin/dub describe
{
	"rootPackage": "d",
	"configuration": "library",
	"buildType": "debug",
	"compiler": "dmd",
	"architecture": [
		"x86_64"
	],
	"platform": [
		"linux",
		"posix"
	],
	"packages": [
		{
			"path": "/home/[username]/workspace/[project]/",
			"name": "d",
			"version": "~master",
			"description": "Hello World - A minimal DUB bundle.",
			"homepage": "",
			"authors": [],
			"copyright": "",
			"license": "",
			"dependencies": [],
			"active": true,
			"configuration": "library",
			"targetType": "library",
			"targetPath": "",
			"targetName": "d",
			"targetFileName": "libd.a",
			"workingDirectory": "",
			"mainSourceFile": "",
			"dflags": [],
			"lflags": [],
			"libs": [],
			"copyFiles": [],
			"versions": [],
			"debugVersions": [],
			"importPaths": [
				"src/"
			],
			"stringImportPaths": [],
			"preGenerateCommands": [],
			"postGenerateCommands": [],
			"preBuildCommands": [],
			"postBuildCommands": [],
			"buildRequirements": [],
			"options": [],
			"files": [
				{
					"role": "source",
					"path": "src/hello.d"
				}
			]
		}
	],
	"targets": [
		{
			"rootPackage": "d",
			"packages": [
				"d"
			],
			"rootConfiguration": "library",
			"buildSettings": {
				"targetType": 6,
				"targetPath": "/home/[username]/workspace/[project]",
				"targetName": "d",
				"workingDirectory": "",
				"mainSourceFile": "",
				"dflags": [],
				"lflags": [],
				"libs": [],
				"linkerFiles": [],
				"sourceFiles": [
					"/home/[username]/workspace/[project]/src/hello.d"
				],
				"copyFiles": [],
				"versions": [
					"Have_d"
				],
				"debugVersions": [],
				"importPaths": [
					"/home/[usrname]/workspace/[project]/src/"
				],
				"stringImportPaths": [],
				"importFiles": [],
				"stringImportFiles": [],
				"preGenerateCommands": [],
				"postGenerateCommands": [],
				"preBuildCommands": [],
				"postBuildCommands": [],
				"requirements": [],
				"options": [
					"debugMode",
					"debugInfo",
					"warningsAsErrors"
				]
			},
			"dependencies": [],
			"linkDependencies": []
		}
	]
}
  ^^^ Terminated, exit code: 0 ^^^'''

**Comment by bruno-medeiros** [comment]
`.project` is an Eclipse / DDT file, and the `dub describe` output is also related to DDT - but this is irrelevant if when you run `dub build`  on the command-line you don't get an executable. You need to figure out the problem there first, the IDE/editor you are using won't matter.
