### ISSUE TITLE
DMD not found in PATH

### ISSUE THREAD

**Issue by p0nce** [DDT-IDE/DDT#150]
DDT doesn't find DMD :

![capture d ecran 2016-10-20 a 19 01 30](https://cloud.githubusercontent.com/assets/1067485/19581396/f23a393e-972c-11e6-9452-42a1b011c7b6.png)

But DMD is in the PATH:

```
$ dmd --version
DMD64 D Compiler v2.072.0-b2
Copyright (c) 1999-2016 by Digital Mars written by Walter Bright
```

**Comment by bruno-medeiros** [comment]
If using the command line you invoke `dub build` on the project directory, does that work? Also is that Linux or OS X?

**Comment by p0nce** [comment]
`dub build`works. OSX.

**Comment by bruno-medeiros** [comment]
This is not a DDT issue, but rather OSX which has different PATH environment variable for command line apps, and UI apps like Eclipse (similar issue: https://github.com/DDT-IDE/DDT/issues/121#issuecomment-154047064 ). See http://superuser.com/questions/28344/path-env-variable-on-mac-os-x-and-or-eclipse for a possible solution.
