### ISSUE TITLE
Associative Array autocompletition not working

### ISSUE THREAD

**Issue by MakersF** [DDT-IDE/DDT#83]
Simple snippet to reproduce
```D
int[string] a = ["k" : 0];
a.
```

There will be no suggestion relative to associative arrays after the dot.

Bringing up https://github.com/bruno-medeiros/DDT/issues/34 , since it looks like that repository is at least as active as this one (has more watchers, more stars, more forks and more contributors, which lead to assume it's in good health), I believe it would be smart to make a comparison between the current autocompletition abilities of DDT and what DCD can offer. In case there are no regressions, I'm willing to invest some time to refactor DDT autocompletition system to a generic deamon model, plus an implementation that uses DCD (I'm proficient in Java). Provided I'll get some support about DDT architecture and structure. I guess it will be better for DDT, DCD and the D community if you invest your time in making DDT even better without spending time in developing functions that are being developed by someone else in parallel.
Since all we want is better support for developing in D, let's use our spare time efficiently.

Contact me at m8r-a9tr1s@mailinator.com (NOTE: it's a public email. Email are deleted after a few hours and you need a code to access it so, despite being highly improbable someone else than me will look at the email, it's not impossible). Please reply to this issue when you do, so I'm notified that you replayed and I can check the email before it gets deleted

**Comment by bruno-medeiros** [comment]
Moved to #131
